# -*- coding: utf-8 -*-
"""CH03 Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwl-TeXT_s0gNtLU52IYr2tgS5qmFsw4

## Week 3 excercises

### Exercise 1.

Write a function named print_right that takes a string named text as a parameter and prints the string with enough leading spaces that the last letter of the string is in the 40th column of the display.
"""

def print_right (text):
  space_40 = 40 - len(text)
  print(" " * space_40 + text)

print_right("Monty")
print_right("Python's")
print_right("Flying Circus")

"""### Exercise 2.

Write a function called triangle that takes a string and an integer and draws a pyramid with the given height, made up using copies of the string. Here's an example of a pyramid with 5 levels, using the string 'L'.
"""

def triangle(string, n):
    for row in range(1, n + 1):
        print(string * (2*row - 1))

# I had to use AI to help me find a solution. I have no idea how to create this on my own.
# That's what I need to understand moving forward

triangle('L', 5)

"""### Exercise 3.

Write a function called `rectangle` that takes a string and two integers and draws a rectangle with the given width and height, made up using copies of the string. Here's an example of a rectangle with width `5` and height `4`, made up of the string `'H'`.
"""

def rectangle(string, width, height):
    for row in range(height):
        print(string * width)

rectangle('H', 5, 4)

"""### Exercise

The song "99 Bottles of Beer" starts with this verse:

> 99 bottles of beer on the wall  
> 99 bottles of beer  
> Take one down, pass it around  
> 98 bottles of beer on the wall  

Then the second verse is the same, except that it starts with 98 bottles and ends with 97. The song continues -- for a very long time -- until there are 0 bottles of beer.

Write a function called `bottle_verse` that takes a number as a parameter and displays the verse that starts with the given number of bottles.

Hint: Consider starting with a function that can print the first, second, or last line of the verse, and then use it to write `bottle_verse`.
"""

def bottle_verse(verse_num):
  print(str(verse_num) + " bottles of beer on the wall")
  print(str(verse_num) + " bottles of beer")
  print("Take one down, pass it around")
  print(str(verse_num - 1) + " bottles of beer on the wall")

"""Use this function call to display the first verse."""

bottle_verse(99)

"""If you want to print the whole song, you can use this `for` loop, which counts down from `99` to `1`.
You don't have to completely understand this example---we'll learn more about `for` loops and the `range` function later.
"""

for n in range(99, 0, -1):
    bottle_verse(n)
    print()